const colors = {
  light: {
    text: '#0F172A',
    tint: '#2563EB',
    background: '#F8FAFC',
    foreground: '#0F172A',
    card: '#FFFFFF',
    cardForeground: '#0F172A',
    primary: '#1D4ED8',
    primaryForeground: '#FFFFFF',
    secondary: '#EEF2FF',
    secondaryForeground: '#1D4ED8',
    muted: '#F1F5F9',
    mutedForeground: '#64748B',
    accent: '#F59E0B',
    accentForeground: '#FFFFFF',
    destructive: '#DC2626',
    destructiveForeground: '#FFFFFF',
    border: '#E2E8F0',
    input: '#E2E8F0',
    success: '#14B8A6',
    successForeground: '#FFFFFF',
    warning: '#F59E0B',
    warningForeground: '#FFFFFF',
    shadow: 'rgba(15,23,42,0.12)',
  },
  radius: 12,
};

export default colors;
