const colors = {
  light: {
    text: '#1E1E1E',
    tint: '#FF6B00',
    background: '#F8F8F8',
    foreground: '#1E1E1E',
    card: '#FFFFFF',
    cardForeground: '#1E1E1E',
    primary: '#FF6B00',
    primaryForeground: '#FFFFFF',
    secondary: '#FFF3E8',
    secondaryForeground: '#FF6B00',
    muted: '#F0F0F0',
    mutedForeground: '#888888',
    accent: '#FF6B00',
    accentForeground: '#FFFFFF',
    destructive: '#D32F2F',
    destructiveForeground: '#FFFFFF',
    border: '#E5E5E5',
    input: '#E5E5E5',
    success: '#2E7D32',
    successForeground: '#FFFFFF',
    warning: '#E65100',
    warningForeground: '#FFFFFF',
    shadow: 'rgba(0,0,0,0.10)',
  },
  dark: {
    text: '#FFFFFF',
    tint: '#FF6B00',
    background: '#121212',
    foreground: '#FFFFFF',
    card: '#1E1E1E',
    cardForeground: '#FFFFFF',
    primary: '#FF6B00',
    primaryForeground: '#FFFFFF',
    secondary: '#2C1800',
    secondaryForeground: '#FF9A4D',
    muted: '#2C2C2C',
    mutedForeground: '#9E9E9E',
    accent: '#FF6B00',
    accentForeground: '#FFFFFF',
    destructive: '#EF5350',
    destructiveForeground: '#FFFFFF',
    border: '#333333',
    input: '#333333',
    success: '#66BB6A',
    successForeground: '#FFFFFF',
    warning: '#FFA726',
    warningForeground: '#FFFFFF',
    shadow: 'rgba(0,0,0,0.5)',
  },
  radius: 12,
};

export default colors;
